### ISSUE TITLE
ERR_REQUIRE_ESM const wrap = require("wrap-ansi");

### ISSUE THREAD

**Issue by alexblack** [Shopify/cli#3190]
# Issue summary

Often (but not always) when I run `yarn dev` to start the project I get this error below.  This happens to my colleague too on a different computer, on a different project, both are new projects from the shopify remix template.

My colleague reports that if he switches from yarn to npm then the problem goes away.  If I `rm -rf` `node_modules` and `yarn.lock`, then run `yarn` again it usually goes away.

```
➜  shopify-reports git:(main) yarn dev
yarn run v1.22.19
$ prisma generate && prisma migrate deploy
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma

✔ Generated Prisma Client (4.16.2 | library) to ./node_modules/@prisma/client in 46ms
You can now start using Prisma Client in your code. Reference: https://pris.ly/d/client
```
import { PrismaClient } from '@prisma/client'
const prisma = new PrismaClient()
```
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": SQLite database "dev.sqlite" at "file:dev.sqlite"

1 migration found in prisma/migrations


No pending migrations to apply.
$ shopify app dev
/Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/errors/errors/pretty-print.js:4
const wrap = require("wrap-ansi");
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/alex/dev/micro/shopify-reports/node_modules/wrap-ansi/index.js from /Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/errors/errors/pretty-print.js not supported.
Instead change the require of index.js in /Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/errors/errors/pretty-print.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/errors/errors/pretty-print.js:4:14)
    at Object.<anonymous> (/Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/errors/handle.js:7:24)
    at Object.<anonymous> (/Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/errors/index.js:4:16)
    at Object.<anonymous> (/Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/cli-ux/index.js:4:16)
    at Object.<anonymous> (/Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/command.js:7:18)
    at Object.<anonymous> (/Users/alex/dev/micro/shopify-reports/node_modules/@oclif/core/lib/index.js:5:19) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.18.2
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by matteodepalo** [comment]
@Shopify/cli-foundations

**Comment by hoangdanh1998** [comment]
Please, Anyone can help

**Comment by lizzr-ecb** [comment]
Getting the same error when spinning up an app with `yarn create @shopify/app`

**Comment by isaacroldan** [comment]
Hi everyone, this is an existing issue with yarn + workspaces. See it here: https://github.com/yarnpkg/yarn/issues/8068
The workarounds are:
- Remove `yarn.lock` and `node_modules` everytime it happens (it will happen after adding a new dependency)
- Add the `nohoist` config to your package json for the packages that fail (see instructions  [here](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/))
- Not use yarn

**Comment by isaacroldan** [comment]
I'm afraid they are necessary, each extension you add behaves like a different package with its own dependencies. 

The best solution is to update your package.json so that the `workspaces` config looks like this:
```json
"workspaces": {
  "packages": ["extensions/*"],
  "nohoist": ["**/wrap-ansi", "**/string-width"]
},
```

After that:
1. remove `yarn.lock` and `node_modules` again
2. Run `yarn install`
3. It should now work forever

**Comment by alexblack** [comment]
Are you saying that extensions are required? I thought our app didn't need one, so I removed the extensions folder and attempted to remove use of workspaces, but that didn't seem to fix this issue for me.

**Comment by alexblack** [comment]
Ok gotcha, that lines up with what I'm seeing: that workspaces are not
required (unless you're using extensions) but that the issue persists when
not using workspaces.

I'm not sure how to apply your fix given I've removed workspaces from my
package.json but I'll take a look.

**Comment by isaacroldan** [comment]
Just add this to your `package.json` and should be good:
```json
"workspaces": {
  "packages": ["extensions/*"],
  "nohoist": ["**/wrap-ansi", "**/string-width"]
},
```

(and remember to remove yarn.lock and node_moduels do a clean install after)

**Comment by isaacroldan** [comment]
Hey @alexblack sorry for the late reply.
I followed those same steps and it works for me. Did you do `yarn add lodash` or `yarn add lodash -W`? (if it let you do the first one, then you don't have workspaces enabled and the nohoist config will be ignored). Also check that you have `private: true` in your `package.json`

Can you check in your `node_module` folder which dependencies are installed? If nohoist is working you should only have 1 copy of `wrap-ansi-cjs` and `string-width-cjs`. If it didn't work you'll also have a copy of `wrap-ansi` and `string-width`.

If it didn't work is because there is something misconfigured in your package.json

Hope this helps!

**Comment by alexblack** [comment]
Hmm yeah I don't have workspaces setup, I thought I should keep it that way since you'd indicated that was the problem.

So you're saying to fix the issue I need to use/enable workspaces?

**Comment by isaacroldan** [comment]
Yarn is weird and the `nohoist` option is only applied if workspaces are enabled (even if not really used).
Should be enough with adding the workspace config in your package.json and also setting `private: true` in it
