### ISSUE TITLE
[Bug]: `shopify theme console` returns nil for any command I enter, when it should still work

### ISSUE THREAD

**Issue by xmadscientist** [Shopify/cli#3650]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

1. run `shopify theme console --url /product/xyz`
2. activate the console in browser
3. go back to CLI and type `product` to view the product data structure
4. console returns the product data structure

### Actual behavior

1. run `shopify theme console --url /product/xyz`
2. activate the console in browser
3. go back to CLI and type `product` to view the product data structure
4. console returns `nil`

### Verbose output

```shell
2024-04-03T15:51:25.742Z: Running command theme console
  shopify:theme:console init version: @oclif/core@3.19.6 argv: [ '--url', '/products/magnetic-socket-holder', '--verbose' ] +0ms
2024-04-03T15:51:25.778Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2024-04-03T15:51:25.779Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store olsatools-dev.myshopify.com:
[]

2024-04-03T15:51:25.780Z: Getting session store...
2024-04-03T15:51:25.782Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "olsatools-dev.myshopify.com"
  }
}

2024-04-03T15:51:25.783Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-04-03T15:51:25.783Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.58.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-04-03T15:51:26.057Z: Request to https://accounts.shopify.com/oauth/introspection completed in 261 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"51e182f7a9ea316ad49d2fc4cbad36c2"
 - x-request-id: 2aa35425-791d-4098-9072-4d2e9516aaeb-1712159486

2024-04-03T15:51:26.060Z: The identity token is valid: true
2024-04-03T15:51:26.061Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false

2024-04-03T15:51:26.061Z: The current session is valid but needs refresh. Refreshing...
2024-04-03T15:51:26.061Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI7_W1sAYQj662sAZSJggBEhAi4ByxYu9A6IX5MSAbXSC6GhAAY33ic5xN7aExHWpzbpIrEkDea0SJ3oDgfkjR-J63HwCt4rK5WOk6jLV-wlNry3F3VbSRWv1m53ZTuUeCqR7-oZFuqnV_f-eOWKCaGp8cahQN&refresh_token=atkn_CiEI7_W1sAYQ74_UsQaiARIKEABjfeJznE3toTEdanNukisSQCOg6fDOI3z96othGWl6Z-_AFZu9RN99AWMwF2QSTNa5ZdA0mzLfHxlPc5BOZ5B5zbRsb3XGB8TtX90QKMln8wQ&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.58.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-04-03T15:51:26.338Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI7_W1sAYQj662sAZSJggBEhAi4ByxYu9A6IX5MSAbXSC6GhAAY33ic5xN7aExHWpzbpIrEkDea0SJ3oDgfkjR-J63HwCt4rK5WOk6jLV-wlNry3F3VbSRWv1m53ZTuUeCqR7-oZFuqnV_f-eOWKCaGp8cahQN&refresh_token=atkn_CiEI7_W1sAYQ74_UsQaiARIKEABjfeJznE3toTEdanNukisSQCOg6fDOI3z96othGWl6Z-_AFZu9RN99AWMwF2QSTNa5ZdA0mzLfHxlPc5BOZ5B5zbRsb3XGB8TtX90QKMln8wQ&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 275 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"31649ae737e80c720eef9c3277d663d7"
 - x-request-id: 2cdedf73-7f4d-4ab4-8f15-0a72f29badc2-1712159486

2024-04-03T15:51:26.341Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.58.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-04-03T15:51:26.341Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.58.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-04-03T15:51:26.341Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.58.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-04-03T15:51:26.341Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Folsatools-dev.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.58.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-04-03T15:51:26.597Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=**** completed in 254 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"0ebf2e614a32561dcfa19d0f78530062"
 - x-request-id: 797b4857-04cd-4278-9c2a-656f8992904b-1712159486

2024-04-03T15:51:26.604Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=**** completed in 261 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"79f5f5fec93da68d7aebc0f014c87677"
 - x-request-id: 585f3544-5704-457e-a36b-36c491b7a458-1712159486

2024-04-03T15:51:26.611Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Folsatools-dev.myshopify.com%2Fadmin completed in 267 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"e6fac9543e75e3602abf1818af8189eb"
 - x-request-id: 8d6f6491-3fc0-45b1-8b84-ddcb589040c7-1712159486

2024-04-03T15:51:26.614Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=**** completed in 272 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"1dd5f3f495de273a8b0985ea060fb4f1"
 - x-request-id: 352085ba-8071-4b33-b7f0-69685bba3e2c-1712159486

2024-04-03T15:51:26.615Z: Setting session store...
2024-04-03T15:51:26.637Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2024-04-03T15:51:26.637Z: Getting session store...
2024-04-03T15:51:26.638Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2024-04-03T15:51:26.638Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-04-03T15:51:26.638Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.58.1
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-04-03T15:51:26.870Z: Request to https://accounts.shopify.com/oauth/introspection completed in 230 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"19625e9234e31296781f726ec42079da"
 - x-request-id: 5fb80fea-69a6-460e-8911-23ffee4fc4c7-1712159486

2024-04-03T15:51:26.871Z: The identity token is valid: true
2024-04-03T15:51:26.871Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false

╭─ info ────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                       │
│  Activate the Shopify Liquid console in your browser and enter your store password if prompted.       │
│                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────╯

2024-04-03T15:51:26.902Z:
Running system process:
  · Command: /usr/local/opt/ruby/bin/ruby -v
  · Working directory: /Users/olsatools/Documents/Olsa Tools Site Codebase/Shopify Theme Codebase/olsa-tools-shopify-2.0

2024-04-03T15:51:26.914Z:
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle -v
  · Working directory: /Users/olsatools/Documents/Olsa Tools Site Codebase/Shopify Theme Codebase/olsa-tools-shopify-2.0

2024-04-03T15:51:27.079Z: Reading the content of file at /usr/local/Cellar/shopify-cli/3.58.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile...
2024-04-03T15:51:27.082Z:
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle install
  · Working directory: /usr/local/Cellar/shopify-cli/3.58.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby

2024-04-03T15:51:27.408Z:
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle exec /usr/local/opt/ruby/bin/ruby /usr/local/Cellar/shopify-cli/3.58.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify theme console --url /products/magnetic-socket-holder --port 9293 --theme liquid-console-repl-3.58.1
  · Working directory: /Users/olsatools/Documents/Olsa Tools Site Codebase/Shopify Theme Codebase/olsa-tools-shopify-2.0

/usr/local/Cellar/shopify-cli/3.58.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:15: warning: observer was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add observer to your Gemfile or gemspec.
/usr/local/Cellar/shopify-cli/3.58.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:15: warning: webrick was loaded from the standard library, but is not part of the default gems since Ruby 3.0.0. Add webrick to your Gemfile or gemspec.
/usr/local/Cellar/shopify-cli/3.58.1/libexec/lib/node_modules/@shopify/theme/node_modules/@shopify/cli-kit/assets/cli-ruby/bin/shopify:15: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec.
DEBUG GET https://olsatools-dev.myshopify.com/admin/api/unstable/themes.json with request_id: dc7cfe13-b0c8-4e44-bb06-1b07b2adc24c-1712159488
[2024-04-03 09:51:28] INFO  WEBrick 1.7.0
[2024-04-03 09:51:28] INFO  ruby 3.3.0 (2023-12-25) [x86_64-darwin23]
[2024-04-03 09:51:28] INFO  WEBrick::HTTPServer#start: pid=47221 port=9293
DEBUG Refreshing preview _secure_session_id cookie
DEBUG Proxying HEAD https://olsatools-dev.myshopify.com/?preview_theme_id=135569735868&_fd=0&pb=0
DEBUG `-> 302 request_id: a59cfcca-d8a5-4e4d-9737-356f775d9421-1712159489
DEBUG Proxying GET https://olsatools-dev.myshopify.com/?preview_theme_id=135569735868&_fd=0&pb=0
DEBUG `-> 302 request_id: f719f4e0-f298-4d87-b4c5-33fc6f830e00-1712159489
DEBUG Proxying GET https://olsatools-dev.myshopify.com/?_fd=0&pb=0
DEBUG `-> 200 request_id: e649ad8d-16fd-4598-b1da-c59af83a770c-1712159490
DEBUG New _secure_session_id cookie from response
[2024-04-03 09:51:31] INFO  going to shutdown ...
[2024-04-03 09:51:31] INFO  WEBrick::HTTPServer#start done.
Welcome to Shopify Liquid console
(press Ctrl + C to exit)

> product
DEBUG Evaluating result
DEBUG URI: https://olsatools-dev.myshopify.com/products/magnetic-socket-holder?section_id=announcement-bar&_fd=0&pb=0
---
HTTP status: 200
---
Response body:
<div id="shopify-section-announcement-bar" class="shopify-section announcement-bar-section"><link href="//cdn.shopify.com/s/files/1/0531/3459/0140/t/21/assets/component-slideshow.css?v=107725913939919748051697492941" rel="stylesheet" type="text/css" media="all" />
<link href="//cdn.shopify.com/s/files/1/0531/3459/0140/t/21/assets/component-slider.css?v=114212096148022386971697492940" rel="stylesheet" type="text/css" media="all" />


<div
  class="utility-bar color-accent-1 gradient"

>
  <div class="page-width utility-bar__grid"><div class="localization-wrapper">
</div>
  </div>
</div>


</div>
DEBUG Evaluating context
DEBUG URI: https://olsatools-dev.myshopify.com/products/magnetic-socket-holder?section_id=announcement-bar&_fd=0&pb=0
---
HTTP status: 200
---
Response body:
<div id="shopify-section-announcement-bar" class="shopify-section announcement-bar-section"><link href="//cdn.shopify.com/s/files/1/0531/3459/0140/t/21/assets/component-slideshow.css?v=107725913939919748051697492941" rel="stylesheet" type="text/css" media="all" />
<link href="//cdn.shopify.com/s/files/1/0531/3459/0140/t/21/assets/component-slider.css?v=114212096148022386971697492940" rel="stylesheet" type="text/css" media="all" />


<div
  class="utility-bar color-accent-1 gradient"

>
  <div class="page-width utility-bar__grid"><div class="localization-wrapper">
</div>
  </div>
</div>


</div>
DEBUG Evaluating assignment context
DEBUG Evaluating syntax error
DEBUG URI: https://olsatools-dev.myshopify.com/products/magnetic-socket-holder?section_id=announcement-bar&_fd=0&pb=0
---
HTTP status: 200
---
Response body:
<div id="shopify-section-announcement-bar" class="shopify-section announcement-bar-section"><link href="//cdn.shopify.com/s/files/1/0531/3459/0140/t/21/assets/component-slideshow.css?v=107725913939919748051697492941" rel="stylesheet" type="text/css" media="all" />
<link href="//cdn.shopify.com/s/files/1/0531/3459/0140/t/21/assets/component-slider.css?v=114212096148022386971697492940" rel="stylesheet" type="text/css" media="all" />


<div
  class="utility-bar color-accent-1 gradient"

>
  <div class="page-width utility-bar__grid"><div class="localization-wrapper">
</div>
  </div>
</div>


</div>
DEBUG URI: https://olsatools-dev.myshopify.com/products/magnetic-socket-holder?section_id=announcement-bar&_fd=0&pb=0
---
HTTP status: 200
---
Response body:
<div id="shopify-section-announcement-bar" class="shopify-section announcement-bar-section"><link href="//cdn.shopify.com/s/files/1/0531/3459/0140/t/21/assets/component-slideshow.css?v=107725913939919748051697492941" rel="stylesheet" type="text/css" media="all" />
<link href="//cdn.shopify.com/s/files/1/0531/3459/0140/t/21/assets/component-slider.css?v=114212096148022386971697492940" rel="stylesheet" type="text/css" media="all" />


<div
  class="utility-bar color-accent-1 gradient"

>
  <div class="page-width utility-bar__grid"><div class="localization-wrapper">
</div>
  </div>
</div>


</div>
nil
```
```


### Reproduction steps

1. run `shopify theme console --url /product/xyz`
2. activate the console in browser
3. go back to CLI and type `product` to view the product data structure
4. console returns `nil`

### Operating System

Mac OS Ventura

### Shopify CLI version (check your project's `package.json` if you're not sure)

Current Shopify CLI version: 3.58.1

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v14.18.3

### What language and version are you using in your application?

Liquid

**Comment by FavLucas** [comment]
Same problem for me

**Comment by karreiro** [comment]
Thank you for reporting this, @xmadscientist and @FavLucas!

The fix for this issue has been released by [`3.59.1`](https://github.com/Shopify/cli/releases/tag/3.59.1), so upgrading the CLI should resolve the problem:

![image](https://github.com/Shopify/cli/assets/1079279/621f2030-abb5-41d8-b668-f377dee3a6c5)

**Comment by xmadscientist** [comment]
@karreiro now I'm getting a different error. It seems to work properly when using strictly `shopify theme console` as the command, but when I added parameters, I'm getting all kinds of errors. Here's the verbose output:

```
shopify theme console -e=us_staging --url=/products/aluminum-toolbox-emblems --port=9296 --verbose

2024-04-24T22:48:46.757Z: Running command theme console
2024-04-24T22:48:46.766Z: Reading the content of file at shopify.theme.toml...
╭─ info ───────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                      │
│  Using applicable flags from us_staging environment:                                                 │
│                                                                                                      │
│    • store: olsatools.myshopify.com                                                                  │
│    • password: ********8c5c                                                                          │
│                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯

2024-04-24T22:48:46.828Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

╭─ info ───────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                      │
│  Activate the Shopify Liquid console in your browser and enter your store password if prompted.      │
│                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯

2024-04-24T22:48:46.842Z:
Running system process:
  · Command: /usr/local/opt/ruby/bin/ruby -v
  · Working directory: /Users/olsatools/Documents/Olsa Tools Site Codebase/Shopify Theme Codebase/olsa-tools-shopify-2.0

2024-04-24T22:48:46.856Z:
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle -v
  · Working directory: /Users/olsatools/Documents/Olsa Tools Site Codebase/Shopify Theme Codebase/olsa-tools-shopify-2.0

2024-04-24T22:48:47.029Z: Reading the content of file at /usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/Gemfile...
2024-04-24T22:48:47.032Z:
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle install
  · Working directory: /usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby

2024-04-24T22:48:47.569Z:
Running system process:
  · Command: /usr/local/opt/ruby/bin/bundle exec /usr/local/opt/ruby/bin/ruby /usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify theme console --url /products/aluminum-toolbox-emblems --port 9296 --theme liquid-console-repl-3.59.1
  · Working directory: /Users/olsatools/Documents/Olsa Tools Site Codebase/Shopify Theme Codebase/olsa-tools-shopify-2.0

DEBUG GET https://theme-kit-access.shopifyapps.com/cli/admin/api/unstable/themes.json with request_id: 110f308b-edc2-4a38-bb0c-44d8093f1837-1713998928
[2024-04-24 16:48:49] INFO  WEBrick 1.7.0
[2024-04-24 16:48:49] INFO  ruby 3.3.1 (2024-04-23) [x86_64-darwin23]
┏━━ Error ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ The address "http://127.0.0.1:9296" is already in use.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┏━━ Try this ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ Use the --port=PORT option to serve the theme in a different port.
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ~/Documents/Olsa Tools Site Codebase/Shopify Theme Codebase/olsa-tools-shopify-2.0   feat/emblem-wizard                         1 ↵  4281  16:48:49
 $ [2024-04-24 16:48:51] INFO  going to shutdown ...
[2024-04-24 16:48:51] INFO  WEBrick::HTTPServer#start done.
Welcome to Shopify Liquid console
(press Ctrl + C to exit)

▽Shopify Liquid console error: Input/output error
DEBUG ["/usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/reline/ansi.rb:258:in `raw'", "/usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/reline/ansi.rb:258:in `cursor_pos'", "/usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/reline.rb:488:in `may_req_ambiguous_char_width'", "/usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/reline.rb:312:in `inner_readline'", "/usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/reline.rb:288:in `readline'", "/usr/local/Cellar/ruby/3.3.1/lib/ruby/3.3.0/forwardable.rb:240:in `readline'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/repl.rb:63:in `input'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/repl.rb:59:in `snippet'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/repl.rb:53:in `repl'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/repl.rb:42:in `block in run'", "<internal:kernel>:187:in `loop'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/theme/repl.rb:42:in `run'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/project_types/theme/commands/console.rb:19:in `call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/command/sub_command.rb:15:in `call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/command.rb:26:in `call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/executor.rb:17:in `block (2 levels) in call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:37:in `block (2 levels) in with_logging'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui/stdout_router.rb:169:in `with_id'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:36:in `block in with_logging'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-ui/lib/cli/ui.rb:177:in `log_output_to'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:35:in `with_logging'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/executor.rb:16:in `block in call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:45:in `block (2 levels) in with_traps'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:44:in `block in with_traps'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:55:in `twrap'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/executor.rb:43:in `with_traps'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/executor.rb:15:in `call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:17:in `block in call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/monorail.rb:26:in `log'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/lib/shopify_cli/core/entry_point.rb:16:in `call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:57:in `block (2 levels) in <main>'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:75:in `handle_abort'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/vendor/deps/cli-kit/lib/cli/kit/error_handler.rb:21:in `call'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:56:in `block in <main>'", "/usr/local/Cellar/shopify-cli/3.59.1/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:66:in `<main>'"]
```

**Comment by xmadscientist** [comment]
Oh I've tried a bunch of different, unused ports, but it still does the
same thing. When I try to execute on a port, the verification step tries to
open the local server site, but it redirects to my actual site while the
terminal is still awaiting verification. I have to Ctrl + C the process,
then run the same command. Then the proper verification window appears, but
the console says that there's an error.

If you think it'll help, I'm happy to share a screen recording of the issue
so you can see what's happening. It's kinda hard to describe in words lol.

**Comment by sb18281** [comment]
I'm experiencing this also - reported in [3783](https://github.com/Shopify/cli/issues/3783)

**Comment by mgmanzella** [comment]
reopened because not fixed 

@xmadscientist can you run the command @karreiro shared with verbose logs and reshare the console output -- thank you 🙏 
`shopify theme console --port=9299 --verbose`

**Comment by mgmanzella** [comment]
closing this issue as we haven't heard back however if you're still experiencing this problem please re open with what you've tried and the current error you're seeing in `--verbose` logs. thanks 🙏
