### ISSUE TITLE
[Bug]: `theme console` seems to give the wrong login URL

### ISSUE THREAD

**Issue by diegovogel** [Shopify/cli#4316]
### Please confirm that you have:

- [X] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [X] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Theme

### Expected behavior

When I run `shopify theme console` it should give me the correct URL for activating the console.

### Actual behavior

It sends me to `http://localhost:9293/password`, which doesn't seem to do anything. I have to go to `http://localhost:9293` in order to activate the console.

### Verbose output

```shell
2024-08-12T20:28:58.660Z: Running command theme console
2024-08-12T20:28:58.670Z: Ensuring that the user is authenticated with the Theme API with the following scopes:
[]

2024-08-12T20:28:58.670Z: Ensuring that the user is authenticated with the Admin API with the following scopes for the store mbrp-production.myshopify.com:
[]

2024-08-12T20:28:58.671Z: Getting session store...
2024-08-12T20:28:58.672Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "adminApi": {
    "scopes": [],
    "storeFqdn": "mbrp-production.myshopify.com"
  }
}

2024-08-12T20:28:58.672Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-08-12T20:28:58.673Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.65.3
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-08-12T20:28:58.872Z: Request to https://accounts.shopify.com/oauth/introspection completed in 193 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"da1f4d11e6a378ec035c853387223d82"
 - x-request-id: e7e11602-1f13-42c1-9b9c-4330693c0ff4-1723494538

2024-08-12T20:28:58.882Z: The identity token is valid: true
2024-08-12T20:28:58.882Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false

2024-08-12T20:28:58.883Z: The current session is valid but needs refresh. Refreshing...
2024-08-12T20:28:58.883Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI6-DptQYQi5nqtQZSJggBEhBBMEJCxVpA16FdW213_UkbGhDMFkA_z4BPIYmX9bf4SAljEkD-5HCpow40nkgGpHzhtQtSpXrZoqBa3F0Nw9v-MPQyBdOvnnGE_X9G3m23a1fq1J5r5bNiuhcieQ1JLG0svt8M&refresh_token=atkn_CiEI6-DptQYQ6_qHtwaiARIKEMwWQD_PgE8hiZf1t_hICWMSQND3Q7y7shcF0RunBN37u5mIPf7buvvtYiU-GSIIKye3R5zIpUkXF9rOr70wFGJU_F8caVfXMynCTr3lwRiLyQc&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3
With request headers:
 - User-Agent: Shopify CLI; v=3.65.3
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-08-12T20:28:59.094Z: Request to https://accounts.shopify.com/oauth/token?grant_type=refresh_token&access_token=atkn_CjQI6-DptQYQi5nqtQZSJggBEhBBMEJCxVpA16FdW213_UkbGhDMFkA_z4BPIYmX9bf4SAljEkD-5HCpow40nkgGpHzhtQtSpXrZoqBa3F0Nw9v-MPQyBdOvnnGE_X9G3m23a1fq1J5r5bNiuhcieQ1JLG0svt8M&refresh_token=atkn_CiEI6-DptQYQ6_qHtwaiARIKEMwWQD_PgE8hiZf1t_hICWMSQND3Q7y7shcF0RunBN37u5mIPf7buvvtYiU-GSIIKye3R5zIpUkXF9rOr70wFGJU_F8caVfXMynCTr3lwRiLyQc&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3 completed in 209 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"f9b6a1ff4ed9d90a687b4de272473d67"
 - x-request-id: 16bd37c7-1c74-4efa-a2c6-9a34417f3e51-1723494539

2024-08-12T20:28:59.097Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.65.3
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-08-12T20:28:59.097Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.65.3
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-08-12T20:28:59.097Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=****
With request headers:
 - User-Agent: Shopify CLI; v=3.65.3
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-08-12T20:28:59.099Z: Sending POST request to URL https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Fmbrp-production.myshopify.com%2Fadmin
With request headers:
 - User-Agent: Shopify CLI; v=3.65.3
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-08-12T20:28:59.257Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=32ff8ee5-82b8-4d93-9f8a-c6997cefb7dc&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fdestinations.readonly&subject_token=**** completed in 154 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"34f5203f9370968a9781ac41fb15e8dc"
 - x-request-id: 11aed68d-1021-436c-854c-da5a5a04294a-1723494539

2024-08-12T20:28:59.263Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=271e16d403dfa18082ffb3d197bd2b5f4479c3fc32736d69296829cbb28d41a6&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.app.cli.access&subject_token=**** completed in 162 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"0c712852577ccf62ef8f3701b69a5e7e"
 - x-request-id: e709e404-b43a-4e40-b08b-4d4f4aecd7a5-1723494539

2024-08-12T20:28:59.284Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=7ee65a63608843c577db8b23c4d7316ea0a01bd2f7594f8a9c06ea668c1b775c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.graphql+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.admin.themes+https%3A%2F%2Fapi.shopify.com%2Fauth%2Fpartners.collaborator-relationships.readonly&subject_token=****&destination=https%3A%2F%2Fmbrp-production.myshopify.com%2Fadmin completed in 180 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"966f5012300687b5cc7f1d8efc573eed"
 - x-request-id: 7580a053-f714-4752-be25-cdc499f3658c-1723494539

2024-08-12T20:28:59.300Z: Request to https://accounts.shopify.com/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Atoken-exchange&requested_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&subject_token_type=urn%3Aietf%3Aparams%3Aoauth%3Atoken-type%3Aaccess_token&client_id=fbdb2649-e327-4907-8f67-908d24cfd7e3&audience=ee139b3d-5861-4d45-b387-1bc3ada7811c&scope=https%3A%2F%2Fapi.shopify.com%2Fauth%2Fshop.storefront-renderer.devtools&subject_token=**** completed in 198 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"a329623d80bf484a61af6b86d71b6931"
 - x-request-id: 159027c5-f397-4992-857b-1527e57757cf-1723494539

2024-08-12T20:28:59.301Z: Setting session store...
2024-08-12T20:28:59.308Z: Ensuring that the user is authenticated with the Storefront API with the following scopes:
[]

2024-08-12T20:28:59.308Z: Getting session store...
2024-08-12T20:28:59.308Z: Validating existing session against the scopes:
[
  "openid",
  "https://api.shopify.com/auth/shop.admin.graphql",
  "https://api.shopify.com/auth/shop.admin.themes",
  "https://api.shopify.com/auth/partners.collaborator-relationships.readonly",
  "https://api.shopify.com/auth/shop.storefront-renderer.devtools",
  "https://api.shopify.com/auth/partners.app.cli.access",
  "https://api.shopify.com/auth/destinations.readonly"
]
For applications:
{
  "storefrontRendererApi": {
    "scopes": []
  }
}

2024-08-12T20:28:59.309Z: Sending Identity Introspection request to URL: https://accounts.shopify.com/oauth/introspection
2024-08-12T20:28:59.309Z: Sending POST request to URL https://accounts.shopify.com/oauth/introspection
With request headers:
 - User-Agent: Shopify CLI; v=3.65.3
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: darwin
 - Content-Type: application/json

2024-08-12T20:28:59.513Z: Request to https://accounts.shopify.com/oauth/introspection completed in 203 ms
With response headers:
 - cache-control: no-cache, no-store, private, must-revalidate, max-age=0
 - content-type: application/json; charset=utf-8
 - etag: W/"f6507d05148f3b21c388e815aad11558"
 - x-request-id: 26ad7634-44fb-4330-8772-3d1b9dcb7f6c-1723494539

2024-08-12T20:28:59.515Z: The identity token is valid: true
2024-08-12T20:28:59.515Z:
The validation of the token for application/identity completed with the following results:
- It's expired: false
- It's invalid in identity: false

╭─ info ─────────────────────────────────────────────────────────────────────────────╮
│                                                                                    │
│  Activate the Shopify Liquid console in your browser [1] and enter your store      │
│  password if prompted.                                                             │
│                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────╯
[1] http://localhost:9293/password

2024-08-12T20:28:59.553Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/ruby -v
  · Working directory: /Users/diego/Sites/Shopify/mbrp-store

2024-08-12T20:28:59.561Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle -v
  · Working directory: /Users/diego/Sites/Shopify/mbrp-store

2024-08-12T20:28:59.644Z: Reading the content of file at /opt/homebrew/Cellar/shopify-cli/3.65.3/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/Gemfile...
2024-08-12T20:28:59.645Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle install
  · Working directory: /opt/homebrew/Cellar/shopify-cli/3.65.3/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby

2024-08-12T20:28:59.809Z:
Running system process:
  · Command: /opt/homebrew/opt/ruby/bin/bundle exec /opt/homebrew/opt/ruby/bin/ruby /opt/homebrew/Cellar/shopify-cli/3.65.3/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify theme console --url /products/checkered-flag-short-sleeve-black-t-shirt --port 9293 --theme liquid-console-repl-3.65.3
  · Working directory: /Users/diego/Sites/Shopify/mbrp-store

/opt/homebrew/Cellar/shopify-cli/3.65.3/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:15: warning: observer was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add observer to your Gemfile or gemspec.
/opt/homebrew/Cellar/shopify-cli/3.65.3/libexec/lib/node_modules/@shopify/cli/dist/assets/cli-ruby/bin/shopify:15: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec.
DEBUG GET https://mbrp-production.myshopify.com/admin/api/unstable/themes.json with request_id: e976bfd3-0e9d-469e-9103-4e83781b8c60-1723494540
[2024-08-12 16:29:00] INFO  WEBrick 1.7.0
[2024-08-12 16:29:00] INFO  ruby 3.3.4 (2024-07-09) [arm64-darwin23]
[2024-08-12 16:29:00] INFO  WEBrick::HTTPServer#start: pid=44869 port=9293
DEBUG Refreshing preview _shopify_essential cookie
DEBUG Proxying HEAD https://mbrp-production.myshopify.com/?preview_theme_id=143476981986&_fd=0&pb=0
DEBUG `-> 302 request_id: 6e9c0950-8f42-4389-9e70-b7ff63dd51ae-1723494540
DEBUG Proxying GET https://mbrp-production.myshopify.com/?preview_theme_id=143476981986&_fd=0&pb=0
DEBUG `-> 302 request_id: 0729d4c5-9c65-43fd-a6dd-0b5cf3f5ea7c-1723494541
DEBUG Proxying GET https://mbrp-production.myshopify.com/password?_fd=0&pb=0
DEBUG `-> 302 request_id: bc604e2e-c5de-4c7b-84b6-d867ca9c57e5-1723494541
```
```


### Reproduction steps

1. Run `shopify theme console`

### Operating System

macOS 14.5

### Shopify CLI version (check your project's `package.json` if you're not sure)

3.65.3

### Shell

zsh

### Node version (run `node -v` if you're not sure)

v18.0.0

### What language and version are you using in your application?

_No response_

**Comment by karreiro** [comment]
Thank you for reporting this issue, @diegovogel!

This issue has been resolved in the new implementation of the `shopify theme console` command, which now works without requiring users to open the browser.

The new implementation will be available in the next minor release as a dev preview (`shopify theme console --dev-preview`) and will soon replace the official version.

You can start using the new version in the next minor release :)

Thanks again for reporting this!

**Comment by diegovogel** [comment]
@karreiro Thanks, looking forward to trying it out. I was having another issue that might be resolved by this as well. Logging into `theme console` would usually break the connection for `theme dev` (it would ask me to log in again when trying to sync files). The issue would come and go, so I hadn't reported it yet. But if I still have that problem with the dev preview I'll report it.
