### ISSUE TITLE
[Bug]: Developer Console is not loading

### ISSUE THREAD

**Issue by 0zd0** [Shopify/cli#5429]
### Please confirm that you have:

- [x] Searched [existing issues](.) to see if your issue is a duplicate. (If you’ve found a duplicate issue, feel free to add additional information in a comment on it.)
- [x] Reproduced the issue in [the latest CLI version](https://www.npmjs.com/package/@shopify/cli).

### In which of these areas are you experiencing a problem?

Extension

### Expected behavior

Opens the HMR-enabled console when you switch to edit an extension

### Actual behavior

The console takes forever to load

![Image](https://github.com/user-attachments/assets/4342f817-9ea4-49c2-91b9-5881ce12f2b9)

### Verbose output

<details>
  <summary>Verbose output</summary>

  ```
05:20:41 │                extensions │ 2025-02-19T05:20:41.647Z: UI extensions server received a GET request to URL /extensions/e766e480-0d1e-4d71-8c11-6a68f97381e9/admin.product-details.block.render
05:20:45 │                extensions │ 2025-02-19T05:20:45.226Z: UI extensions server received a OPTIONS request to URL /extensions/e766e480-0d1e-4d71-8c11-6a68f97381e9

05:20:45 │  product-parameters-block │ 2025-02-19T05:20:45.237Z: Parsed locales for extension product-parameters-block at /IdeaProjects/poizon-parser/extensions/product-parameters-block

05:20:45 │                extensions │ 2025-02-19T05:20:45.426Z: UI extensions server received a GET request to URL /extensions/e766e480-0d1e-4d71-8c11-6a68f97381e9

05:20:45 │  product-parameters-block │ 2025-02-19T05:20:45.438Z: Parsed locales for extension product-parameters-block at /IdeaProjects/poizon-parser/extensions/product-parameters-block

› Press d │ toggle development store preview: ✔ on
› Press g │ open GraphiQL (Admin API) in your browser
› Press p │ preview in your browser
› Press q │ quit

Preview URL: https://shopify-dev.space/extensions/dev-console
GraphiQL URL: http://localhost:3457/graphiql

2025-02-19T05:20:45.483Z: Getting last updated timestamp for file at ../extensions/product-parameters-block/dist/product-parameters-block.js...
2025-02-19T05:20:45.487Z: Getting last updated timestamp for file at ../.shopify/bundle/013797d5-a807-8d15-ed94-82e26191b4ada9c0c017/dist/product-parameters-block.js...
2025-02-19T05:20:45.674Z: Sending "Partners" GraphQL request:
  query FindAppPreviewMode($apiKey: String!) {
    app(apiKey: $apiKey) {
      developmentStorePreviewEnabled
    }
  }

With variables:
{
  "apiKey": "*****"
}

With request headers:
 - User-Agent: Shopify CLI; v=3.75.0
 - Keep-Alive: timeout=30
 - Sec-CH-UA-PLATFORM: linux
 - Content-Type: application/json
  ```

</details>

### Reproduction steps

1. Create an application with the Remix template
2. Create Admin Block extension in a product
3. Run dev
4. Go to /extensions/dev-console
5. Go to the extension

### Operating System

6.11.8-arch1-2

### Shopify CLI version (`shopify --version`)

3.75.3

### Node version (run `node -v` if you're not sure)

v22.14.0

### What language and version are you using in your application?

Node v22.14.0

**Comment by 0zd0** [comment]
I work at Devcontainer. Everything's okay except for this.
First I fixed the random port and ran /extensions/dev-console on static, now on my domain this panel opens directly. But still couldn't figure out the problem with the console and HMR. As I understood from the source code and logs it sends an update event, but I don't have any connection to react to these events and there are no errors in the browser console either. 

I come in here

![Image](https://github.com/user-attachments/assets/a6abb0a5-5482-4869-9e23-841b427794d7)

I only see my domain request to the extension itself and nothing else happens. At the same time the extension is displayed, but there is no HMR and this developer console is missing

![Image](https://github.com/user-attachments/assets/e3798fe6-0db1-40f9-ac5e-4247e7e0cb7f)

Also the `FindAppPreviewMode` request is sent every 5 seconds, I don't know if it should be like that.

**Comment by 0zd0** [comment]
@gonzaloriestra Yes, I created another partner and everything works there, websocket connects to `/extensions`. Is it possible to fix this in a non working store?

**Comment by gonzaloriestra** [comment]
Great! We don't know yet what's going on, but let us investigate.

**Comment by orindholt** [comment]
Any update on this? I'm still experiencing it. As well as hot reload not working, even though I'm getting successful builds on file saves, in my terminal - I need to run a full hard refresh for new changes to appear not sure if they're related issues though.

**Comment by gonzaloriestra** [comment]
@orindholt could you please create a new issue including reproduction steps and as much info as you can?
